config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sitios do
    resources :reviews
  end

  root to: 'sitios#index'
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :sitio
  belongs_to :user
end

app/models/sitio.rb
class Sitio < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  has_attached_file :sitio_img, styles: { sitio_index: "250x350>", sitio_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :sitio_img, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sitios
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_sitio
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end
  def create
    @review = Review.new(review_params)
    @review.sitio_id = @sitio.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to sitio_path(@sitio)
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if @review.update(review_params)
      redirect_to sitio_path(@sitio)
    else
      render 'edit'
    end
  end
  def destroy
    @review.destroy
    redirect_to sitio_path(@sitio)
  end

  private
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
  def find_sitio
    @sitio = Sitio.find(params[:sitio_id])
  end
  def find_review
    @review = Review.find(params[:id])
  end
end

app/controllers/sitios_controller.rb
class SitiosController < ApplicationController
  before_action :find_sitio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    @sitios = Sitio.all.order("created_at ASC")
  end

  def show
    if @sitio.reviews.blank?
      @average_review = 0
    else
      @average_review = @sitio.reviews.average(:rating).round(2)
    end
  end

  def new
    @sitio = current_user.sitios.build
  end

  def create
    @sitio = current_user.sitios.build(sitio_params)
    if @sitio.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @sitio.update(sitio_params)
      redirect_to sitio_path(@sitio)
    else
      render 'edit'
    end
  end

  def destroy
    @sitio.destroy
    redirect_to root_path
  end

  private
    def sitio_params
      params.require(:sitio).permit(:title, :description, :author, :sitio_img)
    end
    def find_sitio
      @sitio = Sitio.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sitios_helper.rb
module SitiosHelper
end

app/views/home/index.html.erb
<h3>Bienvenido al Portal Red de Amigos por Chiapas</h3>

<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="row main-footer">
  <div class="col s12 center m4 left">
    &copy; 2018 | Red de Amigos por Chiapas
  </div>
  <div class="col s12 m4 center">
    Dirección: <span>Tuxtla Gutiérrez, Chiapas, México</span> <br>
    <span>5a. Oriente Norte, Edificio A, Planta Baja 2,</span> <br>
    <span>Unidad Quetzalcoatl</span>
  </div>
  <div class="col s12 center m2 right">
    <p>Diseño: <%= link_to image_tag("Logo_ACL_cv_250x250v.png", class: "logoacl"), "https://www.facebook.com/Alexis.Crouz", target:'_blank' %> </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="">
  <nav class="">
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo"><%= link_to image_tag("LogoRedAmigoscv.png", id:"logo"), root_path %></a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Afiliarse", new_user_registration_path %></li>
          <li><%= link_to "Ingresar", new_user_session_path %></li>
        <% end %>
      </ul>
      <!-- <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li><%= link_to "Agregar Sitio", new_sitio_path %></li>
        <% end %>
      </ul> -->
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <% if user_signed_in? %>
      <li><%= link_to "Agregar Sitio", new_sitio_path %></li>
      <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Afiliarse", new_user_registration_path %></li>
      <li><%= link_to "Ingresar", new_user_session_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Red de amigos por chiapas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <style type="text/css">
      nav{
        height:70px;
        clear:both;
        box-sizing:border-box;
        margin: 0% 1% 1% 1%;
        padding: 0% 1% 1% 1%;
        width:98%;
          -webkit-border-radius:5px;
          -moz-border-radius:5px;
        border-radius:5px;
        background: rgb(84,83,83); /* Old browsers */
        background: -moz-linear-gradient(top,  rgba(84,83,83,1) 1%, rgba(36,36,36,1) 79%, rgba(36,36,36,1) 100%, rgba(36,36,36,1) 100%, rgba(83,203,241,1) 100%, rgba(83,203,241,1) 100%, rgba(36,36,36,1) 100%, rgba(36,36,36,1) 100%, rgba(36,36,36,1) 100%); /* FF3.6+ */
        background: -webkit-gradient(linear, left top, left bottom, color-stop(1%,rgba(84,83,83,1)), color-stop(79%,rgba(36,36,36,1)), color-stop(100%,rgba(36,36,36,1)), color-stop(100%,rgba(36,36,36,1)), color-stop(100%,rgba(83,203,241,1)), color-stop(100%,rgba(83,203,241,1)), color-stop(100%,rgba(36,36,36,1)), color-stop(100%,rgba(36,36,36,1)), color-stop(100%,rgba(36,36,36,1))); /* Chrome,Safari4+ */
        background: -webkit-linear-gradient(top,  rgba(84,83,83,1) 1%,rgba(36,36,36,1) 79%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%,rgba(83,203,241,1) 100%,rgba(83,203,241,1) 100%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%); /* Chrome10+,Safari5.1+ */
        background: -o-linear-gradient(top,  rgba(84,83,83,1) 1%,rgba(36,36,36,1) 79%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%,rgba(83,203,241,1) 100%,rgba(83,203,241,1) 100%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%); /* Opera 11.10+ */
        background: -ms-linear-gradient(top,  rgba(84,83,83,1) 1%,rgba(36,36,36,1) 79%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%,rgba(83,203,241,1) 100%,rgba(83,203,241,1) 100%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%); /* IE10+ */
        background: linear-gradient(to bottom,  rgba(84,83,83,1) 1%,rgba(36,36,36,1) 79%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%,rgba(83,203,241,1) 100%,rgba(83,203,241,1) 100%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%,rgba(36,36,36,1) 100%); /* W3C */
          -webkit-box-shadow:0px 2px 2px #000;
          -moz-box-shadow:0px 2px 2px #000;
        box-shadow:0px 2px 2px #000;
        color: rgba(#fff,.6);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#545353', endColorstr='#242424',GradientType=0 ); /* IE6-9 */
      }
    </style>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  </head>

  <body class="main">

    <%= render 'layouts/header' %>

    <!-- <section id="banner"></section> -->
    <section id="cuerpo"></section>
    <article class="">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </article>

    <div class="container">
        <%= yield %>
    </div>

    <div class="fixed-action-btn">
      <a class="btn-floating btn-large red">
        <i class="large material-icons">list</i>
      </a>
      <ul>
        <li><a class="btn-floating red" href="https://www.facebook.com/Red.de.Amigos.por.Chiapas" target="_blank"><i class="material-icons">face</i></a></li>
        <li><a class="btn-floating amber darken-3 tooltipped" data-position="top" data-tooltip="961.579.10.83"><i class="material-icons">phone</i></a>
        <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
        <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
      </ul>
    </div>

    <%= render 'layouts/footer' %>


  <script>
      M.AutoInit();
  </script>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@sitio, @sitio.reviews.build]) do |f| %>
  <div id="rating-form">
    <label for="">Calificar</label>
  <!--   <%= f.input :rating %> -->
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, class:"btn grey lighten-1 btn-flat" %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %></p>

  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
        <%= link_to "Editar", edit_sitio_review_path(review.sitio, review), class: "btn amber darken-3" %>
        <%= link_to "Borrar", sitio_review_path(review.sitio, review), method: :delete, data:{confirm: "Está seguro?"}, class: "btn amber darken-3" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col m6 offset-3">
  <div class="edit-review-form">
    <h1>Editar Comentario</h1>
    <%= simple_form_for([@sitio, @review]) do |f| %>
      <div id="rating-form">
        <label>Calificar</label>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, class: "btn white black-text" %>
    <% end %>
  </div>
</div>


<script>
  $('#rating-form').raty({
    path: '/assets',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col s12 m6 offset-m3">
  <div class="new-review-form">
    <h1>Nuevo Comentario</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/sitios/_form.html.erb
<%= simple_form_for @sitio, html: {multipart: true} do |f| %>
  <%= f.file_field :sitio_img %>
  <%= f.input :title, label: "Nombre del Sitio" %>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit, class: 'btn teal darken-1 waves-effect' %>
<% end %>

app/views/sitios/edit.html.erb
<div class="col s12 m6 offset-3">
  <div class="edit-sitio-form">
    <h1>Editar Sitio</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/sitios/index.html.erb
<div class="row">
  <% @sitios.each do |sitio| %>
    <div class="col s12 m4">
      <a href="/sitios/<%= sitio.id %>">
        <%= image_tag sitio.sitio_img.url(:sitio_index), class: "sitio" %>
      </a>
    </div>
  <% end %>
</div>

app/views/sitios/new.html.erb
<div class="col s12 m6 offset-3">
  <div class="new-sitio-form">
    <h1>Nuevo Sitio</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/sitios/show.html.erb
<div class="row">
  <div class="col s12 m5">
    <%= image_tag @sitio.sitio_img.url(:sitio_show), class: "sitio-show" %>
  </div>
  <div class="col s12 m7">
    <div class="sitio-info">
      <h2 class="sitio-title"><%= @sitio.title %></h2>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews">Con base a <%= @sitio.reviews.count %> comentarios</span>
      <p class="sitio-desc"><%= @sitio.description %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m5">
    <!--Comentarios y Rating Reviews/Rating -->
    <div class="reviews">
      <h3>Comentarios</h3>
      <%= render @sitio.reviews %>
      <div>
        <%= link_to "Add Review", new_sitio_review_path(@sitio), class: "btn grey lighten-1 black-text" %>
      </div>
    </div>
  </div>
</div>

<div class="links btn-group">
  <%= link_to "Back", root_path, class:"btn amber darken-3" %>
  <% if user_signed_in? %>
    <% if @sitio.user_id == current_user.id %>
      <%= link_to "Edit", edit_sitio_path(@sitio), class:"btn amber darken-3" %>
      <%= link_to "Delete", sitio_path(@sitio), method: :delete, data: {confirm: "¿Está seguro de borrar?"}, class:"btn amber darken-3" %>
    <% end %>
  <% end %>
</div>


<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>
<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).attr('data-score')
    }
  });
</script>